"""Add user relationship to Reservation

Revision ID: 558955cbd40e
Revises: 787b3f72c5df
Create Date: 2022-05-20 14:08:44.739975

"""
from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy

# revision identifiers, used by Alembic.
revision = '558955cbd40e'
down_revision = '787b3f72c5df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.add_column(sa.Column(
            'user_id',
            fastapi_users_db_sqlalchemy.guid.GUID(),
            nullable=True
        ))
        batch_op.create_foreign_key(
            'fk_reservation_user_id_user',
            'user',
            ['user_id'],
            ['id']
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.drop_constraint(
            'fk_reservation_user_id_user',
            type_='foreignkey'
        )
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
