"""Add description to MeetingRoom

Revision ID: c6f830e80caf
Revises: b1b5224cfca8
Create Date: 2022-05-16 15:53:52.807724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6f830e80caf'
down_revision = 'b1b5224cfca8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'meetingroom',
        sa.Column('description', sa.Text(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meetingroom', 'description')
    # ### end Alembic commands ###
